// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "deserunt"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "reprehenderit"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "commodo"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "ex"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "voluptate"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "irure"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "fugiat"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "ut"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "non"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "id"
                        });
                });

            modelBuilder.Entity("DAL.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Boink",
                            Price = 3833.54m,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Surelogic",
                            Price = 2334.12m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Opticon",
                            Price = 8289.99m,
                            SupplierId = 9
                        },
                        new
                        {
                            ProductId = 4,
                            Name = "Zanity",
                            Price = 8401.64m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 5,
                            Name = "Bedder",
                            Price = 1241.98m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 6,
                            Name = "Nexgene",
                            Price = 7916.11m,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            Name = "Nixelt",
                            Price = 1303.18m,
                            SupplierId = 13
                        },
                        new
                        {
                            ProductId = 8,
                            Name = "Artworlds",
                            Price = 4923.18m,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            Name = "Accusage",
                            Price = 3562.65m,
                            SupplierId = 22
                        },
                        new
                        {
                            ProductId = 10,
                            Name = "Mantro",
                            Price = 9309.84m,
                            SupplierId = 21
                        },
                        new
                        {
                            ProductId = 11,
                            Name = "Chillium",
                            Price = 6831.99m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 12,
                            Name = "Moreganic",
                            Price = 2983.7m,
                            SupplierId = 12
                        },
                        new
                        {
                            ProductId = 13,
                            Name = "Tropoli",
                            Price = 8489.11m,
                            SupplierId = 9
                        },
                        new
                        {
                            ProductId = 14,
                            Name = "Isotrack",
                            Price = 8283.74m,
                            SupplierId = 21
                        },
                        new
                        {
                            ProductId = 15,
                            Name = "Geekus",
                            Price = 6118.15m,
                            SupplierId = 22
                        },
                        new
                        {
                            ProductId = 16,
                            Name = "Sportan",
                            Price = 7256.04m,
                            SupplierId = 18
                        },
                        new
                        {
                            ProductId = 17,
                            Name = "Typhonica",
                            Price = 7623.6m,
                            SupplierId = 21
                        },
                        new
                        {
                            ProductId = 18,
                            Name = "Boilcat",
                            Price = 8049.55m,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 19,
                            Name = "Blurrybus",
                            Price = 9524.25m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 20,
                            Name = "Ecrater",
                            Price = 3909.1m,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductId = 21,
                            Name = "Oatfarm",
                            Price = 4411.55m,
                            SupplierId = 17
                        },
                        new
                        {
                            ProductId = 22,
                            Name = "Gluid",
                            Price = 1117.44m,
                            SupplierId = 11
                        },
                        new
                        {
                            ProductId = 23,
                            Name = "Enjola",
                            Price = 4074.97m,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 24,
                            Name = "Uberlux",
                            Price = 3979.18m,
                            SupplierId = 16
                        },
                        new
                        {
                            ProductId = 25,
                            Name = "Zilla",
                            Price = 9353.77m,
                            SupplierId = 25
                        },
                        new
                        {
                            ProductId = 26,
                            Name = "Cyclonica",
                            Price = 7594.04m,
                            SupplierId = 18
                        },
                        new
                        {
                            ProductId = 27,
                            Name = "Xiix",
                            Price = 8325.61m,
                            SupplierId = 16
                        },
                        new
                        {
                            ProductId = 28,
                            Name = "Xoggle",
                            Price = 8733.2m,
                            SupplierId = 18
                        },
                        new
                        {
                            ProductId = 29,
                            Name = "Crustatia",
                            Price = 3964.4m,
                            SupplierId = 22
                        },
                        new
                        {
                            ProductId = 30,
                            Name = "Eschoir",
                            Price = 1223.93m,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 31,
                            Name = "Atgen",
                            Price = 6174.73m,
                            SupplierId = 14
                        },
                        new
                        {
                            ProductId = 32,
                            Name = "Dragbot",
                            Price = 1303.88m,
                            SupplierId = 22
                        },
                        new
                        {
                            ProductId = 33,
                            Name = "Papricut",
                            Price = 5969.92m,
                            SupplierId = 25
                        },
                        new
                        {
                            ProductId = 34,
                            Name = "Geologix",
                            Price = 2590.71m,
                            SupplierId = 9
                        },
                        new
                        {
                            ProductId = 35,
                            Name = "Incubus",
                            Price = 4580.29m,
                            SupplierId = 22
                        },
                        new
                        {
                            ProductId = 36,
                            Name = "Pyramax",
                            Price = 5252.72m,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductId = 37,
                            Name = "Earbang",
                            Price = 6453.25m,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductId = 38,
                            Name = "Rugstars",
                            Price = 4765.96m,
                            SupplierId = 12
                        },
                        new
                        {
                            ProductId = 39,
                            Name = "Nurali",
                            Price = 8673.03m,
                            SupplierId = 24
                        },
                        new
                        {
                            ProductId = 40,
                            Name = "Viagrand",
                            Price = 2601.61m,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 41,
                            Name = "Geekmosis",
                            Price = 7220.78m,
                            SupplierId = 18
                        },
                        new
                        {
                            ProductId = 42,
                            Name = "Squish",
                            Price = 4457.24m,
                            SupplierId = 3
                        },
                        new
                        {
                            ProductId = 43,
                            Name = "Tingles",
                            Price = 1791.16m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 44,
                            Name = "Iplax",
                            Price = 8820.49m,
                            SupplierId = 25
                        },
                        new
                        {
                            ProductId = 45,
                            Name = "Apex",
                            Price = 5523.95m,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 46,
                            Name = "Turnabout",
                            Price = 4304.38m,
                            SupplierId = 14
                        },
                        new
                        {
                            ProductId = 47,
                            Name = "Fangold",
                            Price = 6593.9m,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 48,
                            Name = "Premiant",
                            Price = 2970.63m,
                            SupplierId = 10
                        },
                        new
                        {
                            ProductId = 49,
                            Name = "Viocular",
                            Price = 6769.67m,
                            SupplierId = 23
                        },
                        new
                        {
                            ProductId = 50,
                            Name = "Zenco",
                            Price = 9851.62m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 51,
                            Name = "Pawnagra",
                            Price = 7088.94m,
                            SupplierId = 24
                        },
                        new
                        {
                            ProductId = 52,
                            Name = "Lunchpod",
                            Price = 4265.59m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 53,
                            Name = "Quintity",
                            Price = 5317.28m,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 54,
                            Name = "Gronk",
                            Price = 3174.8m,
                            SupplierId = 8
                        },
                        new
                        {
                            ProductId = 55,
                            Name = "Enquility",
                            Price = 8132.19m,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 56,
                            Name = "Singavera",
                            Price = 9677.02m,
                            SupplierId = 5
                        },
                        new
                        {
                            ProductId = 57,
                            Name = "Animalia",
                            Price = 2476.81m,
                            SupplierId = 14
                        },
                        new
                        {
                            ProductId = 58,
                            Name = "Cipromox",
                            Price = 6505.58m,
                            SupplierId = 8
                        },
                        new
                        {
                            ProductId = 59,
                            Name = "Fortean",
                            Price = 7793.87m,
                            SupplierId = 24
                        },
                        new
                        {
                            ProductId = 60,
                            Name = "Aquazure",
                            Price = 8351.02m,
                            SupplierId = 6
                        },
                        new
                        {
                            ProductId = 61,
                            Name = "Nurplex",
                            Price = 8005.16m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 62,
                            Name = "Opportech",
                            Price = 4351.48m,
                            SupplierId = 18
                        },
                        new
                        {
                            ProductId = 63,
                            Name = "Digitalus",
                            Price = 2484.5m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 64,
                            Name = "Zepitope",
                            Price = 9028.79m,
                            SupplierId = 14
                        },
                        new
                        {
                            ProductId = 65,
                            Name = "Sequitur",
                            Price = 3946.79m,
                            SupplierId = 10
                        },
                        new
                        {
                            ProductId = 66,
                            Name = "Webiotic",
                            Price = 8612.11m,
                            SupplierId = 8
                        },
                        new
                        {
                            ProductId = 67,
                            Name = "Liquidoc",
                            Price = 3746.67m,
                            SupplierId = 7
                        },
                        new
                        {
                            ProductId = 68,
                            Name = "Datacator",
                            Price = 9180.44m,
                            SupplierId = 23
                        },
                        new
                        {
                            ProductId = 69,
                            Name = "Lumbrex",
                            Price = 4060.57m,
                            SupplierId = 22
                        },
                        new
                        {
                            ProductId = 70,
                            Name = "Cinaster",
                            Price = 8559.78m,
                            SupplierId = 14
                        },
                        new
                        {
                            ProductId = 71,
                            Name = "Ecraze",
                            Price = 7677.83m,
                            SupplierId = 9
                        },
                        new
                        {
                            ProductId = 72,
                            Name = "Aclima",
                            Price = 4961.85m,
                            SupplierId = 15
                        },
                        new
                        {
                            ProductId = 73,
                            Name = "Nikuda",
                            Price = 6249.87m,
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 74,
                            Name = "Isoternia",
                            Price = 6164.25m,
                            SupplierId = 13
                        },
                        new
                        {
                            ProductId = 75,
                            Name = "Farmage",
                            Price = 6151.61m,
                            SupplierId = 8
                        },
                        new
                        {
                            ProductId = 76,
                            Name = "Sarasonic",
                            Price = 4321.39m,
                            SupplierId = 21
                        },
                        new
                        {
                            ProductId = 77,
                            Name = "Imant",
                            Price = 3653.63m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 78,
                            Name = "Musanpoly",
                            Price = 6915.35m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 79,
                            Name = "Orbixtar",
                            Price = 6351.83m,
                            SupplierId = 8
                        },
                        new
                        {
                            ProductId = 80,
                            Name = "Extro",
                            Price = 5168.13m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 81,
                            Name = "Volax",
                            Price = 1966.41m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 82,
                            Name = "Vurbo",
                            Price = 3998.04m,
                            SupplierId = 7
                        },
                        new
                        {
                            ProductId = 83,
                            Name = "Fanfare",
                            Price = 2133.37m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 84,
                            Name = "Geofarm",
                            Price = 6360.86m,
                            SupplierId = 12
                        },
                        new
                        {
                            ProductId = 85,
                            Name = "Arctiq",
                            Price = 6872.43m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 86,
                            Name = "Savvy",
                            Price = 2039.21m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 87,
                            Name = "Inrt",
                            Price = 4533.57m,
                            SupplierId = 8
                        },
                        new
                        {
                            ProductId = 88,
                            Name = "Emtrak",
                            Price = 6233.53m,
                            SupplierId = 20
                        },
                        new
                        {
                            ProductId = 89,
                            Name = "Netplax",
                            Price = 6091.68m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 90,
                            Name = "Evidends",
                            Price = 6289.83m,
                            SupplierId = 19
                        },
                        new
                        {
                            ProductId = 91,
                            Name = "Kyagoro",
                            Price = 4981.13m,
                            SupplierId = 25
                        },
                        new
                        {
                            ProductId = 92,
                            Name = "Menbrain",
                            Price = 7938.13m,
                            SupplierId = 10
                        },
                        new
                        {
                            ProductId = 93,
                            Name = "Opticall",
                            Price = 4266.36m,
                            SupplierId = 21
                        },
                        new
                        {
                            ProductId = 94,
                            Name = "Interfind",
                            Price = 9211.84m,
                            SupplierId = 17
                        },
                        new
                        {
                            ProductId = 95,
                            Name = "Adornica",
                            Price = 1218.75m,
                            SupplierId = 14
                        },
                        new
                        {
                            ProductId = 96,
                            Name = "Pathways",
                            Price = 7637.38m,
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 97,
                            Name = "Senmei",
                            Price = 1848.41m,
                            SupplierId = 4
                        },
                        new
                        {
                            ProductId = 98,
                            Name = "Manufact",
                            Price = 2951.69m,
                            SupplierId = 23
                        },
                        new
                        {
                            ProductId = 99,
                            Name = "Comstar",
                            Price = 4589.45m,
                            SupplierId = 12
                        },
                        new
                        {
                            ProductId = 100,
                            Name = "Progenex",
                            Price = 5823.79m,
                            SupplierId = 11
                        });
                });

            modelBuilder.Entity("DAL.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryId = 1,
                            CategoryId = 1,
                            ProductId = 76
                        },
                        new
                        {
                            ProductCategoryId = 2,
                            CategoryId = 3,
                            ProductId = 89
                        },
                        new
                        {
                            ProductCategoryId = 3,
                            CategoryId = 6,
                            ProductId = 13
                        },
                        new
                        {
                            ProductCategoryId = 4,
                            CategoryId = 7,
                            ProductId = 48
                        },
                        new
                        {
                            ProductCategoryId = 5,
                            CategoryId = 8,
                            ProductId = 1
                        },
                        new
                        {
                            ProductCategoryId = 6,
                            CategoryId = 8,
                            ProductId = 30
                        },
                        new
                        {
                            ProductCategoryId = 7,
                            CategoryId = 7,
                            ProductId = 44
                        },
                        new
                        {
                            ProductCategoryId = 8,
                            CategoryId = 8,
                            ProductId = 73
                        },
                        new
                        {
                            ProductCategoryId = 9,
                            CategoryId = 10,
                            ProductId = 39
                        },
                        new
                        {
                            ProductCategoryId = 10,
                            CategoryId = 9,
                            ProductId = 20
                        },
                        new
                        {
                            ProductCategoryId = 11,
                            CategoryId = 6,
                            ProductId = 31
                        },
                        new
                        {
                            ProductCategoryId = 12,
                            CategoryId = 9,
                            ProductId = 62
                        },
                        new
                        {
                            ProductCategoryId = 13,
                            CategoryId = 10,
                            ProductId = 37
                        },
                        new
                        {
                            ProductCategoryId = 14,
                            CategoryId = 8,
                            ProductId = 36
                        },
                        new
                        {
                            ProductCategoryId = 15,
                            CategoryId = 4,
                            ProductId = 54
                        },
                        new
                        {
                            ProductCategoryId = 16,
                            CategoryId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            ProductCategoryId = 17,
                            CategoryId = 3,
                            ProductId = 10
                        },
                        new
                        {
                            ProductCategoryId = 18,
                            CategoryId = 8,
                            ProductId = 87
                        },
                        new
                        {
                            ProductCategoryId = 19,
                            CategoryId = 1,
                            ProductId = 70
                        },
                        new
                        {
                            ProductCategoryId = 20,
                            CategoryId = 6,
                            ProductId = 35
                        },
                        new
                        {
                            ProductCategoryId = 21,
                            CategoryId = 5,
                            ProductId = 66
                        },
                        new
                        {
                            ProductCategoryId = 22,
                            CategoryId = 2,
                            ProductId = 22
                        },
                        new
                        {
                            ProductCategoryId = 23,
                            CategoryId = 6,
                            ProductId = 57
                        },
                        new
                        {
                            ProductCategoryId = 24,
                            CategoryId = 1,
                            ProductId = 7
                        },
                        new
                        {
                            ProductCategoryId = 25,
                            CategoryId = 3,
                            ProductId = 54
                        },
                        new
                        {
                            ProductCategoryId = 26,
                            CategoryId = 7,
                            ProductId = 14
                        },
                        new
                        {
                            ProductCategoryId = 27,
                            CategoryId = 6,
                            ProductId = 57
                        },
                        new
                        {
                            ProductCategoryId = 28,
                            CategoryId = 1,
                            ProductId = 73
                        },
                        new
                        {
                            ProductCategoryId = 29,
                            CategoryId = 10,
                            ProductId = 59
                        },
                        new
                        {
                            ProductCategoryId = 30,
                            CategoryId = 2,
                            ProductId = 68
                        },
                        new
                        {
                            ProductCategoryId = 31,
                            CategoryId = 3,
                            ProductId = 95
                        },
                        new
                        {
                            ProductCategoryId = 32,
                            CategoryId = 8,
                            ProductId = 11
                        },
                        new
                        {
                            ProductCategoryId = 33,
                            CategoryId = 5,
                            ProductId = 36
                        },
                        new
                        {
                            ProductCategoryId = 34,
                            CategoryId = 4,
                            ProductId = 26
                        },
                        new
                        {
                            ProductCategoryId = 35,
                            CategoryId = 6,
                            ProductId = 83
                        },
                        new
                        {
                            ProductCategoryId = 36,
                            CategoryId = 10,
                            ProductId = 75
                        },
                        new
                        {
                            ProductCategoryId = 37,
                            CategoryId = 4,
                            ProductId = 93
                        },
                        new
                        {
                            ProductCategoryId = 38,
                            CategoryId = 7,
                            ProductId = 93
                        },
                        new
                        {
                            ProductCategoryId = 39,
                            CategoryId = 5,
                            ProductId = 46
                        },
                        new
                        {
                            ProductCategoryId = 40,
                            CategoryId = 2,
                            ProductId = 7
                        },
                        new
                        {
                            ProductCategoryId = 41,
                            CategoryId = 8,
                            ProductId = 40
                        },
                        new
                        {
                            ProductCategoryId = 42,
                            CategoryId = 6,
                            ProductId = 67
                        },
                        new
                        {
                            ProductCategoryId = 43,
                            CategoryId = 8,
                            ProductId = 97
                        },
                        new
                        {
                            ProductCategoryId = 44,
                            CategoryId = 7,
                            ProductId = 32
                        },
                        new
                        {
                            ProductCategoryId = 45,
                            CategoryId = 2,
                            ProductId = 43
                        },
                        new
                        {
                            ProductCategoryId = 46,
                            CategoryId = 6,
                            ProductId = 65
                        },
                        new
                        {
                            ProductCategoryId = 47,
                            CategoryId = 3,
                            ProductId = 17
                        },
                        new
                        {
                            ProductCategoryId = 48,
                            CategoryId = 7,
                            ProductId = 59
                        },
                        new
                        {
                            ProductCategoryId = 49,
                            CategoryId = 2,
                            ProductId = 80
                        },
                        new
                        {
                            ProductCategoryId = 50,
                            CategoryId = 1,
                            ProductId = 43
                        },
                        new
                        {
                            ProductCategoryId = 51,
                            CategoryId = 5,
                            ProductId = 73
                        },
                        new
                        {
                            ProductCategoryId = 52,
                            CategoryId = 10,
                            ProductId = 5
                        },
                        new
                        {
                            ProductCategoryId = 53,
                            CategoryId = 3,
                            ProductId = 57
                        },
                        new
                        {
                            ProductCategoryId = 54,
                            CategoryId = 10,
                            ProductId = 59
                        },
                        new
                        {
                            ProductCategoryId = 55,
                            CategoryId = 7,
                            ProductId = 100
                        },
                        new
                        {
                            ProductCategoryId = 56,
                            CategoryId = 2,
                            ProductId = 24
                        },
                        new
                        {
                            ProductCategoryId = 57,
                            CategoryId = 5,
                            ProductId = 42
                        },
                        new
                        {
                            ProductCategoryId = 58,
                            CategoryId = 3,
                            ProductId = 8
                        },
                        new
                        {
                            ProductCategoryId = 59,
                            CategoryId = 4,
                            ProductId = 27
                        },
                        new
                        {
                            ProductCategoryId = 60,
                            CategoryId = 5,
                            ProductId = 74
                        },
                        new
                        {
                            ProductCategoryId = 61,
                            CategoryId = 8,
                            ProductId = 55
                        },
                        new
                        {
                            ProductCategoryId = 62,
                            CategoryId = 7,
                            ProductId = 28
                        },
                        new
                        {
                            ProductCategoryId = 63,
                            CategoryId = 8,
                            ProductId = 30
                        },
                        new
                        {
                            ProductCategoryId = 64,
                            CategoryId = 6,
                            ProductId = 17
                        },
                        new
                        {
                            ProductCategoryId = 65,
                            CategoryId = 7,
                            ProductId = 82
                        },
                        new
                        {
                            ProductCategoryId = 66,
                            CategoryId = 8,
                            ProductId = 45
                        },
                        new
                        {
                            ProductCategoryId = 67,
                            CategoryId = 8,
                            ProductId = 7
                        },
                        new
                        {
                            ProductCategoryId = 68,
                            CategoryId = 4,
                            ProductId = 86
                        },
                        new
                        {
                            ProductCategoryId = 69,
                            CategoryId = 9,
                            ProductId = 8
                        },
                        new
                        {
                            ProductCategoryId = 70,
                            CategoryId = 1,
                            ProductId = 96
                        },
                        new
                        {
                            ProductCategoryId = 71,
                            CategoryId = 5,
                            ProductId = 45
                        },
                        new
                        {
                            ProductCategoryId = 72,
                            CategoryId = 5,
                            ProductId = 41
                        },
                        new
                        {
                            ProductCategoryId = 73,
                            CategoryId = 7,
                            ProductId = 100
                        },
                        new
                        {
                            ProductCategoryId = 74,
                            CategoryId = 4,
                            ProductId = 67
                        },
                        new
                        {
                            ProductCategoryId = 75,
                            CategoryId = 7,
                            ProductId = 83
                        },
                        new
                        {
                            ProductCategoryId = 76,
                            CategoryId = 8,
                            ProductId = 78
                        },
                        new
                        {
                            ProductCategoryId = 77,
                            CategoryId = 9,
                            ProductId = 7
                        },
                        new
                        {
                            ProductCategoryId = 78,
                            CategoryId = 8,
                            ProductId = 24
                        },
                        new
                        {
                            ProductCategoryId = 79,
                            CategoryId = 3,
                            ProductId = 91
                        },
                        new
                        {
                            ProductCategoryId = 80,
                            CategoryId = 8,
                            ProductId = 84
                        },
                        new
                        {
                            ProductCategoryId = 81,
                            CategoryId = 6,
                            ProductId = 76
                        },
                        new
                        {
                            ProductCategoryId = 82,
                            CategoryId = 6,
                            ProductId = 14
                        },
                        new
                        {
                            ProductCategoryId = 83,
                            CategoryId = 1,
                            ProductId = 91
                        },
                        new
                        {
                            ProductCategoryId = 84,
                            CategoryId = 8,
                            ProductId = 40
                        },
                        new
                        {
                            ProductCategoryId = 85,
                            CategoryId = 10,
                            ProductId = 63
                        },
                        new
                        {
                            ProductCategoryId = 86,
                            CategoryId = 10,
                            ProductId = 76
                        },
                        new
                        {
                            ProductCategoryId = 87,
                            CategoryId = 2,
                            ProductId = 46
                        },
                        new
                        {
                            ProductCategoryId = 88,
                            CategoryId = 9,
                            ProductId = 56
                        },
                        new
                        {
                            ProductCategoryId = 89,
                            CategoryId = 9,
                            ProductId = 5
                        },
                        new
                        {
                            ProductCategoryId = 90,
                            CategoryId = 8,
                            ProductId = 16
                        },
                        new
                        {
                            ProductCategoryId = 91,
                            CategoryId = 7,
                            ProductId = 88
                        },
                        new
                        {
                            ProductCategoryId = 92,
                            CategoryId = 2,
                            ProductId = 40
                        },
                        new
                        {
                            ProductCategoryId = 93,
                            CategoryId = 8,
                            ProductId = 59
                        },
                        new
                        {
                            ProductCategoryId = 94,
                            CategoryId = 6,
                            ProductId = 77
                        },
                        new
                        {
                            ProductCategoryId = 95,
                            CategoryId = 5,
                            ProductId = 25
                        },
                        new
                        {
                            ProductCategoryId = 96,
                            CategoryId = 10,
                            ProductId = 17
                        },
                        new
                        {
                            ProductCategoryId = 97,
                            CategoryId = 5,
                            ProductId = 36
                        },
                        new
                        {
                            ProductCategoryId = 98,
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            ProductCategoryId = 99,
                            CategoryId = 1,
                            ProductId = 40
                        },
                        new
                        {
                            ProductCategoryId = 100,
                            CategoryId = 1,
                            ProductId = 94
                        },
                        new
                        {
                            ProductCategoryId = 101,
                            CategoryId = 6,
                            ProductId = 81
                        },
                        new
                        {
                            ProductCategoryId = 102,
                            CategoryId = 5,
                            ProductId = 23
                        },
                        new
                        {
                            ProductCategoryId = 103,
                            CategoryId = 9,
                            ProductId = 33
                        },
                        new
                        {
                            ProductCategoryId = 104,
                            CategoryId = 5,
                            ProductId = 89
                        },
                        new
                        {
                            ProductCategoryId = 105,
                            CategoryId = 4,
                            ProductId = 99
                        },
                        new
                        {
                            ProductCategoryId = 106,
                            CategoryId = 7,
                            ProductId = 95
                        },
                        new
                        {
                            ProductCategoryId = 107,
                            CategoryId = 3,
                            ProductId = 24
                        },
                        new
                        {
                            ProductCategoryId = 108,
                            CategoryId = 5,
                            ProductId = 44
                        },
                        new
                        {
                            ProductCategoryId = 109,
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            ProductCategoryId = 110,
                            CategoryId = 4,
                            ProductId = 71
                        },
                        new
                        {
                            ProductCategoryId = 111,
                            CategoryId = 6,
                            ProductId = 50
                        },
                        new
                        {
                            ProductCategoryId = 112,
                            CategoryId = 6,
                            ProductId = 3
                        },
                        new
                        {
                            ProductCategoryId = 113,
                            CategoryId = 10,
                            ProductId = 6
                        },
                        new
                        {
                            ProductCategoryId = 114,
                            CategoryId = 3,
                            ProductId = 51
                        },
                        new
                        {
                            ProductCategoryId = 115,
                            CategoryId = 7,
                            ProductId = 27
                        },
                        new
                        {
                            ProductCategoryId = 116,
                            CategoryId = 9,
                            ProductId = 3
                        },
                        new
                        {
                            ProductCategoryId = 117,
                            CategoryId = 5,
                            ProductId = 70
                        },
                        new
                        {
                            ProductCategoryId = 118,
                            CategoryId = 6,
                            ProductId = 38
                        },
                        new
                        {
                            ProductCategoryId = 119,
                            CategoryId = 10,
                            ProductId = 53
                        },
                        new
                        {
                            ProductCategoryId = 120,
                            CategoryId = 6,
                            ProductId = 8
                        },
                        new
                        {
                            ProductCategoryId = 121,
                            CategoryId = 6,
                            ProductId = 41
                        },
                        new
                        {
                            ProductCategoryId = 122,
                            CategoryId = 10,
                            ProductId = 84
                        },
                        new
                        {
                            ProductCategoryId = 123,
                            CategoryId = 2,
                            ProductId = 11
                        },
                        new
                        {
                            ProductCategoryId = 124,
                            CategoryId = 5,
                            ProductId = 34
                        },
                        new
                        {
                            ProductCategoryId = 125,
                            CategoryId = 8,
                            ProductId = 15
                        },
                        new
                        {
                            ProductCategoryId = 126,
                            CategoryId = 8,
                            ProductId = 49
                        },
                        new
                        {
                            ProductCategoryId = 127,
                            CategoryId = 1,
                            ProductId = 87
                        },
                        new
                        {
                            ProductCategoryId = 128,
                            CategoryId = 8,
                            ProductId = 6
                        },
                        new
                        {
                            ProductCategoryId = 129,
                            CategoryId = 2,
                            ProductId = 65
                        },
                        new
                        {
                            ProductCategoryId = 130,
                            CategoryId = 7,
                            ProductId = 25
                        },
                        new
                        {
                            ProductCategoryId = 131,
                            CategoryId = 10,
                            ProductId = 62
                        },
                        new
                        {
                            ProductCategoryId = 132,
                            CategoryId = 10,
                            ProductId = 48
                        },
                        new
                        {
                            ProductCategoryId = 133,
                            CategoryId = 2,
                            ProductId = 85
                        },
                        new
                        {
                            ProductCategoryId = 134,
                            CategoryId = 2,
                            ProductId = 63
                        },
                        new
                        {
                            ProductCategoryId = 135,
                            CategoryId = 5,
                            ProductId = 40
                        },
                        new
                        {
                            ProductCategoryId = 136,
                            CategoryId = 7,
                            ProductId = 46
                        },
                        new
                        {
                            ProductCategoryId = 137,
                            CategoryId = 4,
                            ProductId = 24
                        },
                        new
                        {
                            ProductCategoryId = 138,
                            CategoryId = 1,
                            ProductId = 3
                        },
                        new
                        {
                            ProductCategoryId = 139,
                            CategoryId = 8,
                            ProductId = 20
                        },
                        new
                        {
                            ProductCategoryId = 140,
                            CategoryId = 2,
                            ProductId = 84
                        },
                        new
                        {
                            ProductCategoryId = 141,
                            CategoryId = 4,
                            ProductId = 79
                        },
                        new
                        {
                            ProductCategoryId = 142,
                            CategoryId = 5,
                            ProductId = 74
                        },
                        new
                        {
                            ProductCategoryId = 143,
                            CategoryId = 7,
                            ProductId = 57
                        },
                        new
                        {
                            ProductCategoryId = 144,
                            CategoryId = 9,
                            ProductId = 45
                        },
                        new
                        {
                            ProductCategoryId = 145,
                            CategoryId = 6,
                            ProductId = 91
                        },
                        new
                        {
                            ProductCategoryId = 146,
                            CategoryId = 4,
                            ProductId = 95
                        },
                        new
                        {
                            ProductCategoryId = 147,
                            CategoryId = 3,
                            ProductId = 66
                        },
                        new
                        {
                            ProductCategoryId = 148,
                            CategoryId = 1,
                            ProductId = 83
                        },
                        new
                        {
                            ProductCategoryId = 149,
                            CategoryId = 7,
                            ProductId = 54
                        },
                        new
                        {
                            ProductCategoryId = 150,
                            CategoryId = 3,
                            ProductId = 18
                        },
                        new
                        {
                            ProductCategoryId = 151,
                            CategoryId = 2,
                            ProductId = 93
                        },
                        new
                        {
                            ProductCategoryId = 152,
                            CategoryId = 2,
                            ProductId = 10
                        },
                        new
                        {
                            ProductCategoryId = 153,
                            CategoryId = 8,
                            ProductId = 45
                        },
                        new
                        {
                            ProductCategoryId = 154,
                            CategoryId = 1,
                            ProductId = 64
                        },
                        new
                        {
                            ProductCategoryId = 155,
                            CategoryId = 8,
                            ProductId = 51
                        },
                        new
                        {
                            ProductCategoryId = 156,
                            CategoryId = 5,
                            ProductId = 41
                        },
                        new
                        {
                            ProductCategoryId = 157,
                            CategoryId = 7,
                            ProductId = 55
                        },
                        new
                        {
                            ProductCategoryId = 158,
                            CategoryId = 9,
                            ProductId = 35
                        },
                        new
                        {
                            ProductCategoryId = 159,
                            CategoryId = 7,
                            ProductId = 3
                        },
                        new
                        {
                            ProductCategoryId = 160,
                            CategoryId = 4,
                            ProductId = 82
                        },
                        new
                        {
                            ProductCategoryId = 161,
                            CategoryId = 9,
                            ProductId = 78
                        },
                        new
                        {
                            ProductCategoryId = 162,
                            CategoryId = 1,
                            ProductId = 87
                        },
                        new
                        {
                            ProductCategoryId = 163,
                            CategoryId = 6,
                            ProductId = 36
                        },
                        new
                        {
                            ProductCategoryId = 164,
                            CategoryId = 9,
                            ProductId = 4
                        },
                        new
                        {
                            ProductCategoryId = 165,
                            CategoryId = 8,
                            ProductId = 1
                        },
                        new
                        {
                            ProductCategoryId = 166,
                            CategoryId = 9,
                            ProductId = 13
                        },
                        new
                        {
                            ProductCategoryId = 167,
                            CategoryId = 8,
                            ProductId = 81
                        },
                        new
                        {
                            ProductCategoryId = 168,
                            CategoryId = 6,
                            ProductId = 74
                        },
                        new
                        {
                            ProductCategoryId = 169,
                            CategoryId = 8,
                            ProductId = 12
                        },
                        new
                        {
                            ProductCategoryId = 170,
                            CategoryId = 6,
                            ProductId = 19
                        },
                        new
                        {
                            ProductCategoryId = 171,
                            CategoryId = 8,
                            ProductId = 1
                        },
                        new
                        {
                            ProductCategoryId = 172,
                            CategoryId = 10,
                            ProductId = 94
                        },
                        new
                        {
                            ProductCategoryId = 173,
                            CategoryId = 1,
                            ProductId = 30
                        },
                        new
                        {
                            ProductCategoryId = 174,
                            CategoryId = 2,
                            ProductId = 76
                        },
                        new
                        {
                            ProductCategoryId = 175,
                            CategoryId = 4,
                            ProductId = 96
                        },
                        new
                        {
                            ProductCategoryId = 176,
                            CategoryId = 6,
                            ProductId = 12
                        },
                        new
                        {
                            ProductCategoryId = 177,
                            CategoryId = 9,
                            ProductId = 98
                        },
                        new
                        {
                            ProductCategoryId = 178,
                            CategoryId = 9,
                            ProductId = 77
                        },
                        new
                        {
                            ProductCategoryId = 179,
                            CategoryId = 1,
                            ProductId = 48
                        },
                        new
                        {
                            ProductCategoryId = 180,
                            CategoryId = 1,
                            ProductId = 90
                        },
                        new
                        {
                            ProductCategoryId = 181,
                            CategoryId = 6,
                            ProductId = 13
                        },
                        new
                        {
                            ProductCategoryId = 182,
                            CategoryId = 5,
                            ProductId = 24
                        },
                        new
                        {
                            ProductCategoryId = 183,
                            CategoryId = 7,
                            ProductId = 70
                        },
                        new
                        {
                            ProductCategoryId = 184,
                            CategoryId = 9,
                            ProductId = 92
                        },
                        new
                        {
                            ProductCategoryId = 185,
                            CategoryId = 1,
                            ProductId = 85
                        },
                        new
                        {
                            ProductCategoryId = 186,
                            CategoryId = 5,
                            ProductId = 74
                        },
                        new
                        {
                            ProductCategoryId = 187,
                            CategoryId = 6,
                            ProductId = 66
                        },
                        new
                        {
                            ProductCategoryId = 188,
                            CategoryId = 2,
                            ProductId = 100
                        },
                        new
                        {
                            ProductCategoryId = 189,
                            CategoryId = 4,
                            ProductId = 92
                        },
                        new
                        {
                            ProductCategoryId = 190,
                            CategoryId = 8,
                            ProductId = 91
                        },
                        new
                        {
                            ProductCategoryId = 191,
                            CategoryId = 9,
                            ProductId = 5
                        },
                        new
                        {
                            ProductCategoryId = 192,
                            CategoryId = 2,
                            ProductId = 67
                        },
                        new
                        {
                            ProductCategoryId = 193,
                            CategoryId = 8,
                            ProductId = 7
                        },
                        new
                        {
                            ProductCategoryId = 194,
                            CategoryId = 5,
                            ProductId = 65
                        },
                        new
                        {
                            ProductCategoryId = 195,
                            CategoryId = 2,
                            ProductId = 79
                        },
                        new
                        {
                            ProductCategoryId = 196,
                            CategoryId = 6,
                            ProductId = 74
                        },
                        new
                        {
                            ProductCategoryId = 197,
                            CategoryId = 5,
                            ProductId = 25
                        },
                        new
                        {
                            ProductCategoryId = 198,
                            CategoryId = 4,
                            ProductId = 58
                        },
                        new
                        {
                            ProductCategoryId = 199,
                            CategoryId = 5,
                            ProductId = 35
                        },
                        new
                        {
                            ProductCategoryId = 200,
                            CategoryId = 6,
                            ProductId = 85
                        });
                });

            modelBuilder.Entity("DAL.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            City = "Cedarville",
                            Country = "Samoa",
                            SupplierName = "AQUASURE"
                        },
                        new
                        {
                            SupplierId = 2,
                            City = "Rockbridge",
                            Country = "Tajikistan",
                            SupplierName = "ZILLANET"
                        },
                        new
                        {
                            SupplierId = 3,
                            City = "Dorneyville",
                            Country = "Chile",
                            SupplierName = "GEEKULAR"
                        },
                        new
                        {
                            SupplierId = 4,
                            City = "Ladera",
                            Country = "Angola",
                            SupplierName = "ZENSUS"
                        },
                        new
                        {
                            SupplierId = 5,
                            City = "Darlington",
                            Country = "Brazil",
                            SupplierName = "OLYMPIX"
                        },
                        new
                        {
                            SupplierId = 6,
                            City = "Garberville",
                            Country = "Croatia (Hrvatska)",
                            SupplierName = "ZEAM"
                        },
                        new
                        {
                            SupplierId = 7,
                            City = "Islandia",
                            Country = "Comoros",
                            SupplierName = "ZOINAGE"
                        },
                        new
                        {
                            SupplierId = 8,
                            City = "Fairlee",
                            Country = "Peru",
                            SupplierName = "BRAINQUIL"
                        },
                        new
                        {
                            SupplierId = 9,
                            City = "Springhill",
                            Country = "Senegal",
                            SupplierName = "INSURON"
                        },
                        new
                        {
                            SupplierId = 10,
                            City = "Hackneyville",
                            Country = "Kyrgyzstan",
                            SupplierName = "AVENETRO"
                        },
                        new
                        {
                            SupplierId = 11,
                            City = "Farmington",
                            Country = "Sri Lanka",
                            SupplierName = "COMVEYOR"
                        },
                        new
                        {
                            SupplierId = 12,
                            City = "Innsbrook",
                            Country = "Honduras",
                            SupplierName = "NETUR"
                        },
                        new
                        {
                            SupplierId = 13,
                            City = "Ezel",
                            Country = "Costa Rica",
                            SupplierName = "SIGNIDYNE"
                        },
                        new
                        {
                            SupplierId = 14,
                            City = "Watrous",
                            Country = "French Guiana",
                            SupplierName = "VETRON"
                        },
                        new
                        {
                            SupplierId = 15,
                            City = "Macdona",
                            Country = "Fiji",
                            SupplierName = "BRAINCLIP"
                        },
                        new
                        {
                            SupplierId = 16,
                            City = "Croom",
                            Country = "Trinidad and Tobago",
                            SupplierName = "DAYCORE"
                        },
                        new
                        {
                            SupplierId = 17,
                            City = "Rose",
                            Country = "Austria",
                            SupplierName = "ZENTRY"
                        },
                        new
                        {
                            SupplierId = 18,
                            City = "Springdale",
                            Country = "Anguilla",
                            SupplierName = "KENEGY"
                        },
                        new
                        {
                            SupplierId = 19,
                            City = "Thatcher",
                            Country = "Hong Kong",
                            SupplierName = "ZYTREX"
                        },
                        new
                        {
                            SupplierId = 20,
                            City = "Kennedyville",
                            Country = "Sao Tome and Principe",
                            SupplierName = "SOPRANO"
                        },
                        new
                        {
                            SupplierId = 21,
                            City = "Warsaw",
                            Country = "French Polynesia",
                            SupplierName = "KIDSTOCK"
                        },
                        new
                        {
                            SupplierId = 22,
                            City = "Thynedale",
                            Country = "India",
                            SupplierName = "SOFTMICRO"
                        },
                        new
                        {
                            SupplierId = 23,
                            City = "Navarre",
                            Country = "Uganda",
                            SupplierName = "FURNIGEER"
                        },
                        new
                        {
                            SupplierId = 24,
                            City = "Cumminsville",
                            Country = "Falkland Islands (Malvinas)",
                            SupplierName = "ROTODYNE"
                        },
                        new
                        {
                            SupplierId = 25,
                            City = "Gadsden",
                            Country = "Brunei Darussalam",
                            SupplierName = "ASSISTIA"
                        });
                });

            modelBuilder.Entity("DAL.Models.Product", b =>
                {
                    b.HasOne("DAL.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.ProductCategory", b =>
                {
                    b.HasOne("DAL.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
